### ISSUE TITLE
Math doesn't match

### ISSUE THREAD

**Issue by gabegodoy** [Thiagolino8/PERT#2]
Tomando como base o artigo no TabNews, o resultado fornecido está abaixo do esperado.

Para exemplicar:

Valor otimista: 1 dia.
Valor mais provável: 3 dias.
Valor pessimista: 6 dias.

R = (1 + (4 x 3) + 6) / 6
R = (1 + 12 + 6) / 6
R = 19 / 6
R = 3,1666666667

Enquanto na aplicação: The expected time to complete the task is 2.17 days

**Comment by Thiagolino8** [comment]
Obrigado pelo aviso, mais provável e otimista estavam trocados
